CREATE TABLE IF NOT EXISTS margin_templates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  inverter_margin DECIMAL(8,4) NOT NULL DEFAULT 0,
  panel_margin DECIMAL(8,4) NOT NULL DEFAULT 0,
  battery_margin DECIMAL(8,4) NOT NULL DEFAULT 0,
  safety_margin DECIMAL(8,4) NOT NULL DEFAULT 0,
  mounting_margin DECIMAL(8,4) NOT NULL DEFAULT 0,
  installation_margin DECIMAL(8,4) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
