UPDATE audit_logs
SET module='CRM'
WHERE module='QUOTES';

UPDATE audit_logs
SET module='AM'
WHERE module='BUDGET'
  AND action IN (
    'ACCOUNT_CREATED',
    'ACCOUNT_UPDATED',
    'ACCOUNT_DEACTIVATED',
    'ACCOUNT_DELETED',
    'BOOKKEEPING_CREATED',
    'BOOKKEEPING_UPDATED',
    'BOOKKEEPING_DELETED'
  );

UPDATE audit_logs
SET module='FM'
WHERE module='BUDGET'
  AND action IN (
    'RAW_LOGS_EXPORTED',
    'TRANSACTION_CREATED',
    'TRANSACTIONS_CREATED',
    'TRANSACTION_UPDATED',
    'TRANSACTION_DELETED',
    'TRANSACTIONS_BULK_DELETED',
    'TRANSACTIONS_PROJECT_ASSIGNED',
    'EXCEL_IMPORTED',
    'IMPORT_BATCH_DELETED'
  );

UPDATE audit_logs
SET module='SC'
WHERE module IN ('TEMPLATES', 'MATERIALS', 'INVENTORY', 'PACKAGES', 'MARGINS');

UPDATE audit_logs
SET module='SA'
WHERE module IN ('USERS', 'ROLES');
